name: Vulture (dead code)
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: vulture
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scavenge
        uses: anaynayak/python-vulture-action@v1.0
        id: vulture
        with:
          vulture-args: ./ --min-confidence 90